export const testfile = {
  ObjectStates: [
    {
      Name: "Deck",
      Nickname: "Discovery Deck",
      Description: "",
      Transform: {
        posX: 0,
        posY: 0,
        posZ: 0,
        rotX: 0,
        rotY: 180,
        rotZ: 180,
        scaleX: 1.0238095238095237,
        scaleY: 1,
        scaleZ: 1.0238095238095237,
      },
      DeckIDs: [
        100, 100, 100, 101, 101, 101, 102, 102, 102, 103, 103, 103, 104, 104,
        104, 105, 105, 105, 106, 106, 106, 107, 107, 107, 108, 108, 108, 109,
        109, 109, 110, 110, 111, 111, 112, 112, 113, 113, 114, 114, 115, 115,
        116, 116, 117, 117, 118, 118, 119, 119, 120, 120, 121, 121, 122, 122,
        123, 123, 124, 124, 125, 125, 126, 126, 127, 127, 128, 128, 129, 130,
        131, 132, 133, 134, 135, 136, 137, 138, 139, 200, 201,
      ],
      ContainedObjects: [
        {
          CardID: 100,
          Name: "card",
          Nickname: "starlight scanning",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 100,
          Name: "card",
          Nickname: "starlight scanning",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 100,
          Name: "card",
          Nickname: "starlight scanning",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 101,
          Name: "card",
          Nickname: "nebula observation",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 101,
          Name: "card",
          Nickname: "nebula observation",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 101,
          Name: "card",
          Nickname: "nebula observation",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 102,
          Name: "card",
          Nickname: "cosmic echoes",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 102,
          Name: "card",
          Nickname: "cosmic echoes",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 102,
          Name: "card",
          Nickname: "cosmic echoes",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 103,
          Name: "card",
          Nickname: "galactic signals",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 103,
          Name: "card",
          Nickname: "galactic signals",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 103,
          Name: "card",
          Nickname: "galactic signals",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 104,
          Name: "card",
          Nickname: "stellar anomalies",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 104,
          Name: "card",
          Nickname: "stellar anomalies",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 104,
          Name: "card",
          Nickname: "stellar anomalies",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 105,
          Name: "card",
          Nickname: "escape pods",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 105,
          Name: "card",
          Nickname: "escape pods",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 105,
          Name: "card",
          Nickname: "escape pods",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 106,
          Name: "card",
          Nickname: "space survey",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 106,
          Name: "card",
          Nickname: "space survey",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 106,
          Name: "card",
          Nickname: "space survey",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 107,
          Name: "card",
          Nickname: "deep space analysis",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 107,
          Name: "card",
          Nickname: "deep space analysis",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 107,
          Name: "card",
          Nickname: "deep space analysis",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 108,
          Name: "card",
          Nickname: "planetary probes",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 108,
          Name: "card",
          Nickname: "planetary probes",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 108,
          Name: "card",
          Nickname: "planetary probes",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 109,
          Name: "card",
          Nickname: "astral mapping",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 109,
          Name: "card",
          Nickname: "astral mapping",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 109,
          Name: "card",
          Nickname: "astral mapping",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 110,
          Name: "card",
          Nickname: "baby boom",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 110,
          Name: "card",
          Nickname: "baby boom",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 111,
          Name: "card",
          Nickname: "galactic cartography",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 111,
          Name: "card",
          Nickname: "galactic cartography",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 112,
          Name: "card",
          Nickname: "star charting",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 112,
          Name: "card",
          Nickname: "star charting",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 113,
          Name: "card",
          Nickname: "solar observation",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 113,
          Name: "card",
          Nickname: "solar observation",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 114,
          Name: "card",
          Nickname: "comet study",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 114,
          Name: "card",
          Nickname: "comet study",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 115,
          Name: "card",
          Nickname: "lunar analysis",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 115,
          Name: "card",
          Nickname: "lunar analysis",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 116,
          Name: "card",
          Nickname: "meteorite collection",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 116,
          Name: "card",
          Nickname: "meteorite collection",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 117,
          Name: "card",
          Nickname: "asteroid minefield",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 117,
          Name: "card",
          Nickname: "asteroid minefield",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 118,
          Name: "card",
          Nickname: "planetary exploration",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 118,
          Name: "card",
          Nickname: "planetary exploration",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 119,
          Name: "card",
          Nickname: "space debris damage",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 119,
          Name: "card",
          Nickname: "space debris damage",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 120,
          Name: "card",
          Nickname: "alien artifacts",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 120,
          Name: "card",
          Nickname: "alien artifacts",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 121,
          Name: "card",
          Nickname: "cosmic debris",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 121,
          Name: "card",
          Nickname: "cosmic debris",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 122,
          Name: "card",
          Nickname: "solar harvesting",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 122,
          Name: "card",
          Nickname: "solar harvesting",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 123,
          Name: "card",
          Nickname: "galactic drift",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 123,
          Name: "card",
          Nickname: "galactic drift",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 124,
          Name: "card",
          Nickname: "lunar eclipse",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 124,
          Name: "card",
          Nickname: "lunar eclipse",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 125,
          Name: "card",
          Nickname: "solar powered irrigation",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 125,
          Name: "card",
          Nickname: "solar powered irrigation",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 126,
          Name: "card",
          Nickname: "stellar winds",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 126,
          Name: "card",
          Nickname: "stellar winds",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 127,
          Name: "card",
          Nickname: "planetary alignments",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 127,
          Name: "card",
          Nickname: "planetary alignments",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 128,
          Name: "card",
          Nickname: "interstellar dust",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 128,
          Name: "card",
          Nickname: "interstellar dust",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 129,
          Name: "card",
          Nickname: "galactic exploration",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 130,
          Name: "card",
          Nickname: "quantum anomaly",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 131,
          Name: "card",
          Nickname: "galactic treaty",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 132,
          Name: "card",
          Nickname: "wormhole rift",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 133,
          Name: "card",
          Nickname: "celestial market",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 134,
          Name: "card",
          Nickname: "technological breakthrough",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 135,
          Name: "card",
          Nickname: "solar flare",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 136,
          Name: "card",
          Nickname: "interstellar diplomacy",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 137,
          Name: "card",
          Nickname: "planetary sanctuary",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 138,
          Name: "card",
          Nickname: "galactic census",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 139,
          Name: "card",
          Nickname: "void storm",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 200,
          Name: "card",
          Nickname: "planetary hypershift",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
        {
          CardID: 201,
          Name: "card",
          Nickname: "space locusts",
          Description: "",
          Transform: {
            posX: 0,
            posY: 0,
            posZ: 0,
            rotX: 0,
            rotY: 180,
            rotZ: 180,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
        },
      ],
      CustomDeck: {
        "1": {
          FaceUrl:
            "https://firebasestorage.googleapis.com/v0/b/card-maker-74ec3.appspot.com/o/images%2FakXo9vBpdMO9XO58FnzRJhk3MrL2%2FTTSFiles%2FhKDNrmq7A7RkD2iJGJ5b_m5bqhuzzpxf_0.png?alt=media&token=43d56103-aec6-4f51-9342-4ef22c286327",
          // FaceUrl: "https://mc-files.cyborggrizzly.com/starburn/board.png",
          BackUrl:
            "https://firebasestorage.googleapis.com/v0/b/card-maker-74ec3.appspot.com/o/images%2FakXo9vBpdMO9XO58FnzRJhk3MrL2%2FTTSFiles%2FhKDNrmq7A7RkD2iJGJ5b_back_m5bqhuzzpxf_0.png?alt=media&token=b6a2adfd-1689-42b8-8f1a-247a5f60f5f8",
          NumWidth: 8,
          NumHeight: 5,
          BackIsHidden: true,
          UniqueBack: false,
          Type: 0,
        },
        "2": {
          FaceUrl:
            "https://firebasestorage.googleapis.com/v0/b/card-maker-74ec3.appspot.com/o/images%2FakXo9vBpdMO9XO58FnzRJhk3MrL2%2FTTSFiles%2FhKDNrmq7A7RkD2iJGJ5b_m5bqhuzzpxf_1.png?alt=media&token=e104c984-0841-4599-a071-4f61a56d3e79",
          BackUrl:
            "https://firebasestorage.googleapis.com/v0/b/card-maker-74ec3.appspot.com/o/images%2FakXo9vBpdMO9XO58FnzRJhk3MrL2%2FTTSFiles%2FhKDNrmq7A7RkD2iJGJ5b_back_m5bqhuzzpxf_1.png?alt=media&token=9e83ad09-ba19-4c2f-9455-b7b769edbeec",
          NumWidth: 8,
          NumHeight: 5,
          BackIsHidden: true,
          UniqueBack: false,
          Type: 0,
        },
      },
    },
  ],
};
